config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
resources :users do
resources :albums do
resources :photos do
  resources :sharings, only: [:new, :create, :destroy]
end
end
end
resources :tags
resources :sharings do
  resources :comments
  resources :likes, only: [:new, :create, :destroy] do
    member do
        get 'id'
    end
  end
end
root to: 'albums#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
#before_create :split_tags
has_and_belongs_to_many :photos, :dependent => :destroy
#serialize :tname, Array
 

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
respond_to :html, :js
def index
	@user=current_user
	@tags=@user.tags
	respond_to do |format|
    format.html
    format.js
  end
end
def new
	@album=Album.find(params[:album_id])
	@photo=@album.photos.find(params[:photo_id])
	@tags=@photo.tags.build
end
def create
	@album=Album.find(params[:album_id])
	@photo=@album.photos.find(params[:photo_id])
		@tags=@photo.tags.build(tag_params)
	if @tags.save
		flash[:success]="The tags were added!"
		redirect_to album_path(@album.id)
	else
		render 'new'
	end
end
def show
	@user=current_user
	
	@tag=Tag.find(params[:id])
	@images=@tag.photos
	respond_to do |format|
    format.html
    format.js
  end
end
def destroy
	@tag=Tag.find(params[:id])
	@tag.destroy
	respond_to do |format|
      format.html { redirect_to tags_path }
      format.json
      format.js   { render :layout => false }
    end
end
private
def tag_params
	params.require(:tags).permit(:tname)
end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_show.html.erb
<div class="container">
<div class="full-width-back"></div>
  <div class="full-width">
<% if @images.present? %>
<% @images.each do|f| %>
	
	<div class="col-sm-6 col-md-4 tag">
    <div class="thumbnail tilt-tag" id="tag_photo_back">
  <p class="topic"><%= f.title %></p>
	<% if /missing.png/.match(f.snaps_url) %>
	<%else%>
	<br><%= link_to image_tag(f.snaps_url(:small)), f.snaps_url %><br>
	<center>
<p class="caption">

<%= link_to user_album_path(@user.id,f.album.id), class: "btn btn-primary pull-bottom", role: "button" do %>
         <i class="glyphicon glyphicon-share-alt"></i> Go To Album
                  <%end%>
</p>
</center>
<%end%>
</div>
</div>
<%end%>
<%else%>
<center>
<h1>NO Photos</h1>
<%= link_to tag_path, :method => 'delete', class: "btn btn-danger delete_tag", role: "button" do %>
         <i class="glyphicon glyphicon-share-alt"></i> Delete
                  <%end%>
</center>
<%end%>
</div>
	
	</div>

app/views/tags/_tags.html.erb
<% @tags.each do |f| %>
<%= link_to tag_path(f.id), remote: true, class: "list-group-item list-group-item-warning" do%><i class="glyphicon glyphicon-tag"></i> <%= f.tname %><span class="badge"><%= f.photos.count %></span>
<%end%>
<%end%>

app/views/tags/index.html.erb
<div class="container">
<div class="jumbotron" id="home">
  <h1>Tags</h1>
  <p>Tags your Photos the way u want may the moments <i class="fa fa-birthday-cake"></i>
 , mood <i class="fa fa-smile-o"></i>
, or may be the weather <i class="fa fa-sun-o"></i> that day
......maybe by something much memorable <i class="fa fa-heartbeat"></i>
..<strong>Just TAG it!!</strong> </p>
 </div>
   

<div class="col-md-3 lists">
<div class="list-group">
<% if @tags.present? %>
<%= render "tags" %>
<%else%>
<li class="list-group-item list-group-item-danger">No Tags</li>
<%end%>
</div>
</div>
<div class="col-md-6" id="pics"></div>
</div>

app/views/tags/show.html.erb
<div class="container">
<ol class="breadcrumb">
  <li><a href="<%= tags_path %>">Tags</a></li>
  <li class="active"><%= @tag.tname %></li>
</ol>
<div class="jumbotron">
<h2><%= @tag.tname %></h2>
</div>


<div class="panel panel-default">
  <!-- Default panel contents ---->
  <div class="panel-heading">Photos</div>
  <div class="panel-body">
<div class="row">
<% @images.each do|f| %>
	
	<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
	<% if /missing.png/.match(f.snaps_url) %>
	<%else%>
	<br><%= link_to image_tag(f.snaps_url(:medium)), f.snaps_url %><br>
	
	
<p class="caption">
<b><%= f.title %></b>
<%= link_to "Go To Album", user_album_path(@user.id,f.album.id), class: "btn btn-primary pull-right", role: "button" %>
</p>
</div>
</div>
<%end%>
<%end%>
</div>
	</div>
	</div>
	</div>

app/views/tags/show.js.erb
$("#pics").html("<%= escape_javascript(render 'show') %>")